#!/usr/bin/env node
/**
 * validate-pack.mjs — AGROSBO Phase 4-5 Fixture Pack Validator
 * Node.js only, no npm installs required.
 * Exit 0 on success, Exit 1 on any error.
 * Writes validation-report.md to the same directory.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACK_DIR = __dirname;

const REQUIRED_FILES = [
  'README.md',
  'source-baseline.json',
  'route-catalog.json',
  'rbac-matrix.json',
  'agent-read-conversations.es.json',
  'agent-write-confirmation-scenarios.es.json',
  'idempotency-replay-cases.json',
  'deployment-and-provider-failure-cases.json',
  'validate-pack.mjs',
  'validation-report.md',
  'manifest.json',
];
// validation-report.md is the OUTPUT of this validator — it may not exist on first run.
// CHK-01 will allow it to be absent if it is being freshly generated.
const GENERATED_FILES = new Set(['validation-report.md']);

const EXPECTED_COUNTS = {
  'agent-read-conversations.es.json': { field: 'cases', min: 48 },
  'agent-write-confirmation-scenarios.es.json': { field: 'cases', min: 36 },
  'idempotency-replay-cases.json': { field: 'cases', min: 24 },
  'deployment-and-provider-failure-cases.json': { field: 'cases', min: 24 },
  'route-catalog.json': { field: 'routes', min: 60 },
};

const REQUIRED_BASELINE_FACTS = [
  { path: ['keyFiles', 'api/src/app.ts', 'routePrefix'], value: '/api' },
  { path: ['keyFiles', 'api/src/idempotency.ts', 'ttlMs'], value: 86400000 },
  { path: ['keyFiles', 'api/src/idempotency.ts', 'replayHeader'], value: 'X-Idempotent-Replay: 1' },
  { path: ['keyFiles', 'api/src/env.ts', 'cognitoJwtStatus'], contains: 'not yet implemented' },
];

const REQUIRED_RBAC_ROLES = ['admin', 'tecnico', 'encargado', 'operario', 'finanzas'];
const PROHIBITED_ROLE_NAMES = ['owner', 'collaborator', 'colaborador'];
const PROHIBITED_ADR018_TERMS = [
  'recomiend.*pesticida',
  'recomiend.*fungicida',
  'diagnóstico definitivo',
  'diagnóstico seguro',
  'COGNITO_CLIENT_ID(?!_)',
];

// ─── utilities ────────────────────────────────────────────────────────────────

function sha256(content) {
  return createHash('sha256').update(content).digest('hex');
}

function readJson(filename) {
  const p = resolve(PACK_DIR, filename);
  const raw = readFileSync(p, 'utf8');
  return { raw, data: JSON.parse(raw) };
}

function getNestedValue(obj, pathArr) {
  return pathArr.reduce((acc, k) => (acc && typeof acc === 'object' ? acc[k] : undefined), obj);
}

// ─── checks ───────────────────────────────────────────────────────────────────

const results = [];
let pass = 0;
let fail = 0;

function check(id, description, fn) {
  try {
    const message = fn();
    results.push({ id, status: 'PASS', description, message: message || 'ok' });
    pass++;
  } catch (err) {
    results.push({ id, status: 'FAIL', description, message: err.message });
    fail++;
  }
}

// CHK-01: All required files present (validation-report.md is generated by this script — allowed to be absent on first run)
check('CHK-01', 'All required files present', () => {
  const missing = REQUIRED_FILES.filter(f => !GENERATED_FILES.has(f) && !existsSync(resolve(PACK_DIR, f)));
  if (missing.length > 0) throw new Error(`Missing files: ${missing.join(', ')}`);
  const generatedMissing = [...GENERATED_FILES].filter(f => !existsSync(resolve(PACK_DIR, f)));
  const note = generatedMissing.length > 0 ? ` (${generatedMissing.join(', ')} will be created by this run)` : '';
  return `All ${REQUIRED_FILES.length - generatedMissing.length} pre-existing files present${note}`;
});

// CHK-02: All JSON files parse without error
const parsed = {};
check('CHK-02', 'All JSON files parse without error', () => {
  const jsonFiles = REQUIRED_FILES.filter(f => f.endsWith('.json'));
  const errors = [];
  for (const f of jsonFiles) {
    try {
      const { raw, data } = readJson(f);
      parsed[f] = { raw, data };
    } catch (err) {
      errors.push(`${f}: ${err.message}`);
    }
  }
  if (errors.length > 0) throw new Error(errors.join('\n'));
  return `All ${jsonFiles.length} JSON files parse ok`;
});

// CHK-03: Case counts meet minimums
check('CHK-03', 'Case counts meet minimums', () => {
  const errors = [];
  for (const [file, spec] of Object.entries(EXPECTED_COUNTS)) {
    if (!parsed[file]) continue;
    const arr = parsed[file].data[spec.field];
    if (!Array.isArray(arr)) {
      errors.push(`${file}: field '${spec.field}' is not an array`);
      continue;
    }
    if (arr.length < spec.min) {
      errors.push(`${file}: ${spec.field}.length=${arr.length} < required ${spec.min}`);
    }
  }
  if (errors.length > 0) throw new Error(errors.join('\n'));
  return Object.entries(EXPECTED_COUNTS)
    .map(([f, s]) => `${f}: ${parsed[f]?.data[s.field]?.length ?? '?'}`)
    .join(', ');
});

// CHK-04: Case ID uniqueness within each file
check('CHK-04', 'Case IDs are unique within each file', () => {
  const errors = [];
  const caseFiles = [
    'agent-read-conversations.es.json',
    'agent-write-confirmation-scenarios.es.json',
    'idempotency-replay-cases.json',
    'deployment-and-provider-failure-cases.json',
  ];
  for (const file of caseFiles) {
    if (!parsed[file]) continue;
    const cases = parsed[file].data.cases || [];
    const ids = cases.map(c => c.id);
    const dupes = ids.filter((id, i) => ids.indexOf(id) !== i);
    if (dupes.length > 0) errors.push(`${file}: duplicate IDs: ${dupes.join(', ')}`);
  }
  if (errors.length > 0) throw new Error(errors.join('\n'));
  return 'No duplicate IDs found';
});

// CHK-05: Case IDs follow expected series
check('CHK-05', 'Case IDs follow expected series patterns', () => {
  const seriesMap = {
    'agent-read-conversations.es.json': /^RC-\d{3}$/,
    'agent-write-confirmation-scenarios.es.json': /^WC-\d{3}$/,
    'idempotency-replay-cases.json': /^IC-\d{3}$/,
    'deployment-and-provider-failure-cases.json': /^DC-\d{3}$/,
  };
  const errors = [];
  for (const [file, pattern] of Object.entries(seriesMap)) {
    if (!parsed[file]) continue;
    const cases = parsed[file].data.cases || [];
    const bad = cases.filter(c => !pattern.test(c.id));
    if (bad.length > 0) errors.push(`${file}: IDs not matching ${pattern}: ${bad.map(c => c.id).join(', ')}`);
  }
  if (errors.length > 0) throw new Error(errors.join('\n'));
  return 'All IDs match expected series patterns';
});

// CHK-06: Source baseline required facts
check('CHK-06', 'source-baseline.json contains required verified facts', () => {
  if (!parsed['source-baseline.json']) throw new Error('source-baseline.json not parsed');
  const data = parsed['source-baseline.json'].data;
  const errors = [];
  for (const fact of REQUIRED_BASELINE_FACTS) {
    const val = getNestedValue(data, fact.path);
    if (fact.value !== undefined && val !== fact.value) {
      errors.push(`${fact.path.join('.')}: expected ${JSON.stringify(fact.value)}, got ${JSON.stringify(val)}`);
    }
    if (fact.contains !== undefined && (typeof val !== 'string' || !val.includes(fact.contains))) {
      errors.push(`${fact.path.join('.')}: expected to contain '${fact.contains}', got ${JSON.stringify(val)}`);
    }
  }
  if (errors.length > 0) throw new Error(errors.join('\n'));
  return `All ${REQUIRED_BASELINE_FACTS.length} baseline facts verified`;
});

// CHK-07: RBAC matrix has all 5 roles
check('CHK-07', 'rbac-matrix.json defines all 5 required roles', () => {
  if (!parsed['rbac-matrix.json']) throw new Error('rbac-matrix.json not parsed');
  const roles = Object.keys(parsed['rbac-matrix.json'].data.roles || {});
  const missing = REQUIRED_RBAC_ROLES.filter(r => !roles.includes(r));
  if (missing.length > 0) throw new Error(`Missing roles: ${missing.join(', ')}`);
  return `Roles present: ${REQUIRED_RBAC_ROLES.join(', ')}`;
});

// CHK-08: Prohibited role names absent from ROLE ASSIGNMENT contexts
// Allowed in: prohibitedRoleNames definition arrays, notes, repo.owner, ADR text
// Prohibited in: roleGuard, effectiveRoles, blocked, role field values
check('CHK-08', 'Prohibited role names absent from role assignment contexts', () => {
  const found = [];
  const roleContextPattern = /"(?:roleGuard|effectiveRoles|blocked|role)"\s*:\s*(?:"([^"]+)"|\[([^\]]+)\])/g;
  for (const [filename, { raw }] of Object.entries(parsed)) {
    let m;
    const re = new RegExp(roleContextPattern.source, 'g');
    while ((m = re.exec(raw)) !== null) {
      const values = (m[1] || m[2] || '').replace(/"/g, '').split(',').map(s => s.trim());
      for (const v of values) {
        if (PROHIBITED_ROLE_NAMES.includes(v.toLowerCase())) {
          found.push(`${filename}: "${v}" used in role assignment context`);
        }
      }
    }
  }
  if (found.length > 0) throw new Error(found.join('\n'));
  return `No prohibited role names in role assignment contexts (allowed in reference/documentation fields)`;
});

// CHK-09: No definitive diagnoses or pesticide recommendations in conversation fixtures
check('CHK-09', 'ADR-018 boundaries respected in conversation fixtures', () => {
  const conversationFiles = [
    'agent-read-conversations.es.json',
    'agent-write-confirmation-scenarios.es.json',
  ];
  const errors = [];
  for (const file of conversationFiles) {
    if (!parsed[file]) continue;
    const cases = parsed[file].data.cases || [];
    for (const c of cases) {
      const caseStr = JSON.stringify(c);
      // Check that non-boundary cases don't make definitive diagnoses
      if (c.category !== 'adr-boundary' && c.category !== 'adr-boundary-write') {
        // Look for unqualified definitive diagnosis claims
        if (/la enfermedad es [a-z]/.test(caseStr) || /definitivamente.*enfermedad/.test(caseStr)) {
          errors.push(`${file} ${c.id}: possible definitive diagnosis claim`);
        }
        // Check that pesticide recommendations are absent
        if (/aplica[r]? .{1,30}fungicida|aplica[r]? .{1,30}herbicida/i.test(caseStr) && c.category !== 'applications-write') {
          errors.push(`${file} ${c.id}: possible pesticide recommendation`);
        }
      }
    }
  }
  if (errors.length > 0) throw new Error(errors.join('\n'));
  return 'No ADR-018 boundary violations detected';
});

// CHK-10: Wrong env var name COGNITO_CLIENT_ID absent (should be COGNITO_APP_CLIENT_ID)
check('CHK-10', 'Incorrect env var COGNITO_CLIENT_ID absent (use COGNITO_APP_CLIENT_ID)', () => {
  const allJson = Object.entries(parsed)
    .filter(([f]) => f !== 'validation-report.md')
    .map(([, p]) => p.raw)
    .join('\n');
  // Match COGNITO_CLIENT_ID that is NOT followed by _ID (i.e., not COGNITO_APP_CLIENT_ID)
  const badMatch = allJson.match(/"COGNITO_CLIENT_ID(?!_)"/g);
  if (badMatch && badMatch.length > 0) {
    throw new Error(`Found incorrect var name "COGNITO_CLIENT_ID" — should be "COGNITO_APP_CLIENT_ID". Occurrences: ${badMatch.length}`);
  }
  return 'COGNITO_APP_CLIENT_ID used correctly throughout';
});

// CHK-11: Route catalog has required health routes
check('CHK-11', 'Route catalog includes health routes as AUTH_PUBLIC', () => {
  if (!parsed['route-catalog.json']) throw new Error('route-catalog.json not parsed');
  const routes = parsed['route-catalog.json'].data.routes || [];
  const healthLive = routes.find(r => r.publicPath === '/api/health/live' && r.method === 'GET');
  const healthReady = routes.find(r => r.publicPath === '/api/health/ready' && r.method === 'GET');
  if (!healthLive) throw new Error('/api/health/live GET not found');
  if (!healthReady) throw new Error('/api/health/ready GET not found');
  if (!healthLive.authPublic) throw new Error('/api/health/live should be authPublic:true');
  if (!healthReady.authPublic) throw new Error('/api/health/ready should be authPublic:true');
  return 'Both health routes present and marked authPublic';
});

// CHK-12: Route catalog /api prefix on all public paths
check('CHK-12', 'All route publicPaths start with /api/', () => {
  if (!parsed['route-catalog.json']) throw new Error('route-catalog.json not parsed');
  const routes = parsed['route-catalog.json'].data.routes || [];
  const bad = routes.filter(r => !r.publicPath.startsWith('/api/'));
  if (bad.length > 0) {
    throw new Error(`Routes without /api/ prefix: ${bad.map(r => r.publicPath).join(', ')}`);
  }
  return `All ${routes.length} routes have /api/ prefix`;
});

// CHK-13: Idempotency cases reference correct TTL and header
// keyConstants lives inside _meta (top-level structure of the file)
check('CHK-13', 'Idempotency cases reference correct constants', () => {
  if (!parsed['idempotency-replay-cases.json']) throw new Error('not parsed');
  const data = parsed['idempotency-replay-cases.json'].data;
  // keyConstants may be at top level or inside _meta
  const meta = data.keyConstants || (data._meta && data._meta.keyConstants) || {};
  if (meta.IDEM_TTL_MS !== 86400000) throw new Error(`IDEM_TTL_MS: expected 86400000, got ${meta.IDEM_TTL_MS}`);
  if (meta.replayHeader !== 'X-Idempotent-Replay: 1') throw new Error(`replayHeader wrong: ${meta.replayHeader}`);
  if (meta.conflictStatus !== 409) throw new Error(`conflictStatus: expected 409, got ${meta.conflictStatus}`);
  if (meta.processingConflictCode !== 'IDEMPOTENCY_IN_PROGRESS') throw new Error(`processingConflictCode wrong`);
  return 'TTL=86400000ms, replay header, 409 conflict code all correct';
});

// CHK-14: Write scenarios reference ADR-015 flow
check('CHK-14', 'Write scenarios include ADR-015 constraints', () => {
  if (!parsed['agent-write-confirmation-scenarios.es.json']) throw new Error('not parsed');
  const cases = parsed['agent-write-confirmation-scenarios.es.json'].data.cases || [];
  const withoutAdr = cases.filter(c => !c.adrConstraints || c.adrConstraints.length === 0);
  if (withoutAdr.length > 0) {
    throw new Error(`Cases without adrConstraints: ${withoutAdr.map(c => c.id).join(', ')}`);
  }
  const withAdr015 = cases.filter(c => c.adrConstraints && c.adrConstraints.some(a => a.includes('ADR-015')));
  if (withAdr015.length < cases.length * 0.8) {
    throw new Error(`Only ${withAdr015.length}/${cases.length} write cases reference ADR-015`);
  }
  return `All ${cases.length} write cases have adrConstraints; ${withAdr015.length} reference ADR-015`;
});

// CHK-15: Deployment cases cover required categories
check('CHK-15', 'Deployment cases cover required failure categories', () => {
  if (!parsed['deployment-and-provider-failure-cases.json']) throw new Error('not parsed');
  const cases = parsed['deployment-and-provider-failure-cases.json'].data.cases || [];
  const categories = [...new Set(cases.map(c => c.category))];
  const required = ['cold-start', 'auth-provider', 'database-failure', 'offline-pwa'];
  const missing = required.filter(r => !categories.includes(r));
  if (missing.length > 0) throw new Error(`Missing categories: ${missing.join(', ')}`);
  return `Categories covered: ${categories.join(', ')}`;
});

// CHK-16: Sensitive actions flagged in write scenarios
check('CHK-16', 'Sensitive write scenarios have sensitiveAction:true and confirmationUI', () => {
  if (!parsed['agent-write-confirmation-scenarios.es.json']) throw new Error('not parsed');
  const cases = parsed['agent-write-confirmation-scenarios.es.json'].data.cases || [];
  const sensitive = cases.filter(c => c.sensitiveAction === true);
  const withoutUI = sensitive.filter(c => {
    const draftStr = JSON.stringify(c.turns || []);
    return !draftStr.includes('reinforced') && !draftStr.includes('sensitiveAction');
  });
  if (withoutUI.length > sensitive.length * 0.3) {
    throw new Error(`${withoutUI.length}/${sensitive.length} sensitive cases lack reinforced confirmation signal`);
  }
  return `${sensitive.length} sensitive cases identified; ${sensitive.length - withoutUI.length} have reinforced confirmation`;
});

// CHK-17: manifest.json exists and has required fields
check('CHK-17', 'manifest.json has required fields', () => {
  if (!parsed['manifest.json']) throw new Error('manifest.json not parsed');
  const m = parsed['manifest.json'].data;
  const required = ['packVersion', 'baselineSha', 'generatedAt', 'files'];
  const missing = required.filter(f => !m[f]);
  if (missing.length > 0) throw new Error(`Missing fields: ${missing.join(', ')}`);
  if (!Array.isArray(m.files) || m.files.length === 0) throw new Error('files array empty');
  return `manifest.json has ${m.files.length} file entries`;
});

// CHK-18: No localhost hardcoded in fixtures
check('CHK-18', 'No localhost URLs hardcoded in fixtures', () => {
  const allJson = Object.values(parsed).map(p => p.raw).join('\n');
  const matches = allJson.match(/localhost:\d+/g);
  if (matches && matches.length > 0) {
    throw new Error(`Found hardcoded localhost URLs: ${[...new Set(matches)].join(', ')}`);
  }
  return 'No hardcoded localhost URLs found';
});

// CHK-19: RBAC gap analysis present
check('CHK-19', 'RBAC matrix includes gap analysis', () => {
  if (!parsed['rbac-matrix.json']) throw new Error('not parsed');
  const gaps = parsed['rbac-matrix.json'].data.gapSummary;
  if (!gaps || !Array.isArray(gaps.gaps) || gaps.gaps.length === 0) {
    throw new Error('gapSummary.gaps is missing or empty');
  }
  return `Gap analysis present with ${gaps.gaps.length} documented gaps`;
});

// CHK-20: Read conversations cover all major resource types
check('CHK-20', 'Read conversations cover all major resource types', () => {
  if (!parsed['agent-read-conversations.es.json']) throw new Error('not parsed');
  const cases = parsed['agent-read-conversations.es.json'].data.cases || [];
  const categories = [...new Set(cases.map(c => c.category))];
  const required = ['blocks-read', 'tasks-read', 'observations-read', 'irrigation-read', 'inventory-read', 'weather-read', 'adr-boundary'];
  const missing = required.filter(r => !categories.includes(r));
  if (missing.length > 0) throw new Error(`Missing read categories: ${missing.join(', ')}`);
  return `Read categories covered: ${categories.join(', ')}`;
});

// ─── write validation-report.md ──────────────────────────────────────────────

const timestamp = new Date().toISOString();
const lines = [
  '# AGROSBO Phase 4-5 Pack — Validation Report',
  '',
  `**Generated:** ${timestamp}`,
  `**Baseline SHA:** 156036a`,
  `**Result:** ${fail === 0 ? '✅ ALL CHECKS PASS' : `❌ ${fail} CHECK(S) FAILED`}`,
  '',
  `**Summary:** ${pass} passed, ${fail} failed, ${results.length} total checks`,
  '',
  '## Check Results',
  '',
  '| ID | Status | Description | Message |',
  '|-----|--------|-------------|---------|',
  ...results.map(r => `| ${r.id} | ${r.status === 'PASS' ? '✅ PASS' : '❌ FAIL'} | ${r.description} | ${r.message.replace(/\n/g, '; ').substring(0, 120)} |`),
  '',
  '## File Sizes',
  '',
  '| File | Bytes | SHA-256 (first 16) |',
  '|------|-------|-------------------|',
];

for (const f of REQUIRED_FILES.filter(x => x.endsWith('.json') || x === 'README.md' || x === 'validate-pack.mjs')) {
  try {
    const p = resolve(PACK_DIR, f);
    if (existsSync(p)) {
      const content = readFileSync(p);
      const hash = sha256(content).substring(0, 16);
      lines.push(`| ${f} | ${content.length.toLocaleString()} | ${hash} |`);
    }
  } catch (_) { /* skip */ }
}

lines.push('', '---', `*Validator: validate-pack.mjs — Node.js ${process.version}*`);

const reportPath = resolve(PACK_DIR, 'validation-report.md');
writeFileSync(reportPath, lines.join('\n'), 'utf8');

// ─── print to stdout ──────────────────────────────────────────────────────────

console.log('\n=== AGROSBO Phase 4-5 Pack Validation ===');
console.log(`Timestamp: ${timestamp}`);
console.log(`Checks: ${pass} passed, ${fail} failed\n`);

for (const r of results) {
  const icon = r.status === 'PASS' ? '✓' : '✗';
  console.log(`${icon} [${r.id}] ${r.description}`);
  if (r.status === 'FAIL') {
    console.log(`      ERROR: ${r.message}`);
  }
}

console.log(`\nValidation report written to: validation-report.md`);
console.log(`Result: ${fail === 0 ? 'ALL CHECKS PASS ✓' : `${fail} FAILURE(S) ✗`}`);

if (fail > 0) {
  process.exit(1);
} else {
  process.exit(0);
}
