/**
 * Validation rules for sync operation identifiers.
 *
 * Convention:
 * - client_op_id: UUID v4 (standard format, generated by client)
 * - temp_entity_id: TEXT, non-empty, max 128 chars, alphanumeric + hyphens + underscores
 *   Allows prefixed IDs like "temp-prod-001" or UUIDs.
 * - server IDs: UUID v4 (generated by PostgreSQL)
 *
 * DISPOSABLE.
 */

const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const TEMP_ID_REGEX = /^[a-zA-Z0-9_-]{1,128}$/;
const MAX_TEMP_ID_LENGTH = 128;

export interface ValidationError {
  field: string;
  message: string;
}

export function validateClientOpId(value: string): ValidationError | null {
  if (!value || !UUID_REGEX.test(value)) {
    return { field: 'client_op_id', message: 'Must be a valid UUID v4' };
  }
  return null;
}

export function validateTempEntityId(value: string): ValidationError | null {
  if (!value) {
    return { field: 'temp_entity_id', message: 'Must not be empty' };
  }
  if (value.length > MAX_TEMP_ID_LENGTH) {
    return {
      field: 'temp_entity_id',
      message: `Must not exceed ${MAX_TEMP_ID_LENGTH} characters (got ${value.length})`,
    };
  }
  if (!TEMP_ID_REGEX.test(value)) {
    return {
      field: 'temp_entity_id',
      message: 'Must contain only alphanumeric characters, hyphens, and underscores',
    };
  }
  return null;
}

export function validateSyncOperation(op: {
  client_op_id: string;
  temp_entity_id: string;
}): ValidationError[] {
  const errors: ValidationError[] = [];
  const opIdErr = validateClientOpId(op.client_op_id);
  if (opIdErr) errors.push(opIdErr);
  const tempIdErr = validateTempEntityId(op.temp_entity_id);
  if (tempIdErr) errors.push(tempIdErr);
  return errors;
}
